- name: Create directory for the mqtt2exporter binary
  file:
    state: directory
    path: /opt/mqtt2exporter/bin

- name: Get mqtt2exporter binary
  get_url:
    url: "{{ lookup('vars', 'mqtt2exporter_binary_' + ansible_machine + '_url') }}"
    dest: /opt/mqtt2exporter/bin/mqtt2exporter
    mode: "0755"

- name: Create directory for the mqtt2exporter device files
  file:
    state: directory
    path: "{{ mqtt2exporter_devices_path }}"

- name: unzip yaml files
  unarchive:
    remote_src: true
    src: "{{ mqtt2exporter_archived_messages }}"
    dest: "{{ mqtt2exporter_devices_path }}"

- name: Create directory for the mqtt2exporter synonym files
  file:
    state: directory
    path: "{{ mqtt2exporter_synonyms_path }}"

- name: create synonyms file
  template:
    src: synonyms.yml.j2
    dest: "{{ mqtt2exporter_synonyms_path }}/synonyms.yml"

- name: create mqtt2exporter service
  template:
     src: mqtt2exporter.service.j2
     dest: /lib/systemd/system/mqtt2exporter.service
     mode: "0644"

- name: install new mqtt2exporter service
  systemd:
    daemon_reload: yes

- name: install new mqtt2exporter service
  systemd:
    enabled: yes
    name: mqtt2exporter
    state: started
